include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AesteaRevived

AesteaRevived_FILES = Tweak.x
AesteaRevived_CFLAGS = -fobjc-arc -Wno-logical-op-parentheses -Wno-c++11-extra-semi
AesteaRevived_FRAMEWORKS = UIKit
AesteaRevived_EXTRA_FRAMEWORKS += Cephei

export AesteaRevived_LIBRARIES = gcuniversal

include $(THEOS_MAKE_PATH)/tweak.mk