BUNDLE_NAME = AesteaPrefs

AesteaPrefs_FILES = $(wildcard **/**/*.m)
AesteaPrefs_CFLAGS = -fobjc-arc
AesteaPrefs_LIBRARIES = gcuniversal
AesteaPrefs_FRAMEWORKS = UIKit
AesteaPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
AesteaPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
