TWEAK_NAME = AesteaPrysm

AesteaPrysm_FILES = AesteaPrysm.m
AesteaPrysm_CFLAGS = -fobjc-arc
AesteaPrysm_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
