TWEAK_NAME = AesteaStock

AesteaStock_FILES = AesteaStock.m
AesteaStock_CFLAGS = -fobjc-arc
AesteaStock_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
