TWEAK_NAME = AesteaRevived

AesteaRevived_FILES = AesteaRevived.x
AesteaRevived_CFLAGS = -fobjc-arc -Wno-logical-op-parentheses -Wno-c++11-extra-semi
AesteaRevived_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk