TWEAK_NAME = AesteaAkara

AesteaAkara_FILES = AesteaAkara.m
AesteaAkara_CFLAGS = -fobjc-arc
AesteaAkara_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk